// Code generated by PIGO8 embedgen; DO NOT EDIT.

package main

import (
	"embed"
	
	p8 "github.com/drpaneas/pigo8"
)

// Embed the game-specific resources
//
//go:embed music0.wav music1.wav music2.wav music3.wav music4.wav music5.wav music6.wav
var resources embed.FS

func init() {
	// Register the embedded resources with PIGO8
	p8.RegisterEmbeddedResources(resources, "", "", "music0.wav", "music1.wav", "music2.wav", "music3.wav", "music4.wav", "music5.wav", "music6.wav")

	// Audio will be automatically initialized if audio files are present
}
