// Code generated by PIGO8 embedgen; DO NOT EDIT.

package main

import (
	"embed"
	
	p8 "github.com/drpaneas/pigo8"
)

// Embed the game-specific resources
//
//go:embed palette.hex
var resources embed.FS

func init() {
	// Register the embedded resources with PIGO8
	p8.RegisterEmbeddedResources(resources, "", "", "palette.hex")

	// Audio will be automatically initialized if audio files are present
}
