// Code generated by PIGO8 embedgen; DO NOT EDIT.

package main

import (
	"embed"
	"log"
	
	p8 "github.com/drpaneas/pigo8"
)

// Embed the game-specific resources
//
//go:embed audio1.wav audio2.wav audio3.wav
var resources embed.FS

func init() {
	// Register the embedded resources with PIGO8
	p8.RegisterEmbeddedResources(resources, "", "", "audio1.wav", "audio2.wav", "audio3.wav")
	
	// Initialize audio player if audio files are present
	if p8.GetAudioPlayer() != nil {
		log.Println("Audio system initialized")
	}
}
