// Code generated by PIGO8 embedgen; DO NOT EDIT.

package main

import (
	"embed"
	"log"
	
	p8 "github.com/drpaneas/pigo8"
)

// Embed the game-specific resources
//
//go:embed spritesheet.json palette.hex
var resources embed.FS

func init() {
	// Register the embedded resources with PIGO8
	p8.RegisterEmbeddedResources(resources, "spritesheet.json", "", "palette.hex")

	// Initialize audio player if audio files are present
	if p8.GetAudioPlayer() != nil {
		log.Println("Audio system initialized")
	}
}
